apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: myissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: support@okteto.com
    preferredChain: ""
    privateKeySecretRef:
      name: okteto-http01
    solvers:
    - http01:
       ingress:
         class: nginx
